spring:
  config:
    activate:
      on-profile: dev

# ===============================
# JWT CONFIG (DEV ONLY)
# ===============================
jwt:
  secret: continuum-dev-secret-key-change-in-prod
  expiration-ms: 86400000

# ===============================
# WEB PUSH (VAPID) CONFIG (DEV)
# ===============================
push:
  vapid:
    public-key: BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjBJuBkr3qBUYIHBQFLXYp5Nksh8U
    private-key: UUxI4O8-FbRouADVXc-hK-l-dR0OYDy3fOY7EHmWnqs
    subject: mailto:dev@continuum.local

jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
