spring:
  application:
    name: Continuum

  profiles:
    group:
      prod-verify: prod

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

# Shared (non-secret) frontend config
frontend-url: ${FRONTEND_URL:http://localhost:5173}
